# Generated by Django 4.2.4 on 2023-08-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                ("date", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("info", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Goods",
            },
        ),
    ]
