# Generated by Django 4.2.4 on 2023-08-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "genre",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "technique",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
